
name = "Base"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "https://www.gurujada.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Gurujada"
  homepage = ""

[original]
  name = ""
  homepage = ""
  repo = ""
